"use strict";
/**
 * Test API Service
 * Sample ASP.NET Core Web API for test purpose
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
exports.ProblemDetails = void 0;
var ProblemDetails = /** @class */ (function (_super) {
    __extends(ProblemDetails, _super);
    function ProblemDetails() {
    }
    ProblemDetails.getAttributeTypeMap = function () {
        return _super.getAttributeTypeMap.call(this).concat(ProblemDetails.attributeTypeMap);
    };
    ProblemDetails.discriminator = undefined;
    ProblemDetails.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string"
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string"
        }
    ];
    return ProblemDetails;
}(null));
exports.ProblemDetails = ProblemDetails;
